
# **Questions 1:**

Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [3]:
import numpy as np

In [4]:
arr = np.arange(2, 53, 3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

# **Question 2:**

Accept two lists of 5 elements each from the user. Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [5]:
A=[11,25,3,4,5]
B=[6,77,8,69,10]
arr1=np.array(A)
arr2=np.array(B)

In [6]:
arr1 #list A converted to array

array([11, 25,  3,  4,  5])

In [7]:
arr2 #list B converted to array

array([ 6, 77,  8, 69, 10])

In [8]:
a=np.concatenate((arr1,arr2)) #array concatenation
a

array([11, 25,  3,  4,  5,  6, 77,  8, 69, 10])

In [9]:
np.sort(a) #sorting of concatenated array

array([ 3,  4,  5,  6,  8, 10, 11, 25, 69, 77])

# **Question 3:**

Write a code snippet to find the dimensions of a ndarray and its size.

In [10]:
b=np.ndarray([3,4,2]) #ndarray
b

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [11]:
np.ndim(b) #dimension of ndarray

3

In [12]:
np.size(b) #size of ndarray

24

# **Question 4:**

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

# *Converting 1D array to 2D array using np.newaxis*

In [13]:
a1 = np.arange(4)
a1.shape

(4,)

In [14]:
row_vec = a1[np.newaxis, :]     # arr[None, :]
row_vec.shape

(1, 4)

In [15]:
row_vec #1D array

array([[0, 1, 2, 3]])

In [16]:
col_vec = a1[:, np.newaxis]     # arr[:, None]
col_vec.shape

(4, 1)

In [17]:
col_vec #converted to 2D array using np.newaxis

array([[0],
       [1],
       [2],
       [3]])

# *Converting 1D array to 2D array using np.expand_dims*

In [18]:
a1

array([0, 1, 2, 3])

In [19]:
np.ndim(a1)

1

In [20]:
a2 = np.expand_dims(a1, axis=(1,-2,3))
a2.shape

(4, 1, 1, 1)

In [21]:
np.ndim(a2)

4

# **Question 5:** 

Consider two square numpy arrays. Stack them vertically and horizontally. Hint: Use vstack(), hstack()

In [22]:
f = np.array([1,2,3])
g = np.array([4,5,6])  

print('Horizontal Append:\n', np.hstack((f, g))) #using hstack()

Horizontal Append:
 [1 2 3 4 5 6]


In [23]:
f = np.array([1,2,3])
g = np.array([4,5,6])  

print('Vertical Append:\n', np.vstack((f, g)))  #using vstack()

Vertical Append:
 [[1 2 3]
 [4 5 6]]


# **Question 6:**

How to get unique items and counts of unique items?

In [24]:
a = np.array( [10,10,20,10,20,20,20,30, 30,50,40,40] )
print("Original array:")
print(a ,"\n")
unique_elements, counts_elements = np.unique(a, return_counts=True)
print("Frequency of unique values of the said array:")
print(np.asarray((unique_elements, counts_elements)))

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40] 

Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]
